### PR TITLE
Configure Renovate

### LINKED ISSUE #23: Update dependencies automatically
Using scala steward/renovate/something else.

### PR DESCRIPTION
**Pull request by andreisilviudragnea**
I suggest using Renovate over Scala Steward because it has better Maven support.

I also suggest using branch automerge, meaning that if CI passes, Renovate commits the change in master branch directly, without creating a PR. It only creates a PR for dependency updates which fail CI.

I have been using Renovate in this configuration on all my repositories and it works flawlessly.

Fixes #23.

### CODE REVIEW

**Comment by andreisilviudragnea** [comment]
@evis

**Comment by andreisilviudragnea** [comment]
@rahulsinghai

**Comment by andreisilviudragnea** [comment]
@evis What do you think about this?

**Comment by evis** [comment]
@andreisilviudragnea is it enough to just add renovate.json config?

I guess that setting up https://github.com/renovatebot/github-action is needed too, isn't it?

**Comment by andreisilviudragnea** [comment]
https://github.com/apps/renovate also needs to be installed with write access to the repository, if you want the bot to also automatically commit updates in master when CI checks pass.

**Comment by evis** [comment]
Let's try this thing out =) It should simplify and speedup release process of the plugin. Thanks!

**Pull request merged**
